version: '3.7'

services:
  fiona_db:
    environment:
      POSTGRES_USER: fiona_user
      POSTGRES_PASSWORD: categoria_5
      POSTGRES_DB: Fiona
    image: postgres:latest
    networks:
      - default
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./initial_data.sql:/docker-entrypoint-initdb.d/initial_data.sql